name: Build Android APK
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        # تم التحديث إلى v4 لتجنب مشاكل Node.js القديم
        uses: actions/checkout@v4

      - name: Set up JDK 17
        # خطوة أساسية لضمان تثبيت جافا بشكل صحيح ومتوافق مع أندرويد
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev
          pip3 install --user --upgrade buildozer cython

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:~/.local/bin/
          # بناء التطبيق مع قبول شروط الـ Android SDK تلقائياً لتفادي توقف البناء
          yes | buildozer android debug

      - name: Upload APK
        # تم التحديث إلى v4 ليتوافق مع باقي الأدوات
        uses: actions/upload-artifact@v4
        with:
          name: Redxfix-APK
          path: bin/*.apk
